  # # version: "3.8"

  # services:
  #   db:
  #     image: postgres:15
  #     container_name: todo_db
  #     environment:
  #       POSTGRES_DB: todo_db
  #       POSTGRES_USER: todo_user
  #       POSTGRES_PASSWORD: password
  #     ports:
  #       - "5432:5432"
  #     volumes:
  #       - todo_data:/var/lib/postgresql/data

  #   app:
  #     build: .
  #     container_name: todo_app
  #     depends_on:
  #       - db
  #     ports:
  #       - "8000:8000"

  # volumes:
  #   todo_data:
    

# version: "3.8"

# services:
#   db:
#     image: postgres:15
#     container_name: todo_db
#     environment:
#       POSTGRES_DB: todo_db
#       POSTGRES_USER: todo_user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - todo_data:/var/lib/postgresql/data

#   app:
#     build: .
#     container_name: todo_app
#     depends_on:
#       - db
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./:/app   # Mount the current project folder into /app in container

# volumes:
#   todo_data: {}   # Correct mapping for named volume

version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://todo_user:password@db:5432/todo_db

volumes:
  todo_data: {}
